version: '2'

services:
  cache:
    image: redis:alpine
    volumes:
      - redis-data:/data

  app:
    image: gcavalcante8808/celery-results-reader
    environment:
      - RESULT_BACKEND_URL
      - BROKER_URL
    ports:
      - 5000:5000
